# Generated by Django 3.2.7 on 2021-11-19 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='email_address',
            new_name='email',
        ),
    ]
